### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/web-api-skeleton.log
      archivedLogFilenamePattern: logs/web-api-skeleton-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1/web-api-skeleton/

subjects:
  backendScheme: https
  backendHost: example.com
  backendPort: 8080
  backendPath: /path/to/api
  backendUsername: secret
  backendPassword: sauce

httpClient:
  timeout: 150000ms #todo: define a better timeout
  connectionTimeout: 15000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 2
  maxConnectionsPerRoute: 2
  keepAlive: 0ms
  retries: 0
  userAgent: subjects-api
